# Generated by Django 5.1.4 on 2024-12-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='help_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
