# Generated by Django 5.1.4 on 2025-01-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_field_field_type_alter_field_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['block_template', 'name']},
        ),
        migrations.AddField(
            model_name='field',
            name='max_numbers',
            field=models.PositiveBigIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='max_symbols',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
    ]
