# Generated by Django 5.1.4 on 2025-01-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_field_options_field_max_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
