# Generated by Django 5.1.4 on 2025-01-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_descriptionfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionfield',
            name='field',
        ),
        migrations.AddField(
            model_name='descriptionfield',
            name='block_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description_fields', to='app.blocktemplate'),
        ),
        migrations.AddField(
            model_name='field',
            name='descriptions',
            field=models.ManyToManyField(blank=True, related_name='fields', to='app.descriptionfield'),
        ),
    ]
