# Generated by Django 5.1.4 on 2025-01-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_field_descriptions_field_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionfield',
            name='block_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description_fields', to='app.blocktemplate'),
        ),
    ]
