# Generated by Django 5.1.4 on 2025-01-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_descriptionfield_block_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='description',
        ),
    ]
