# Generated by Django 5.1.4 on 2025-01-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_field_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='static_value',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Стале значення'),
        ),
    ]
