# Generated by Django 5.1.4 on 2025-01-07 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_field_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={},
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_select', to='app.field')),
            ],
        ),
    ]
