# Generated by Django 5.1.4 on 2025-01-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_field_options_selectoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectOption',
        ),
    ]
