# Generated by Django 5.1.4 on 2025-01-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_field_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='extra_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
