# Generated by Django 5.1.4 on 2025-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_field_extra_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='static_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
