# Generated by Django 5.1.4 on 2025-01-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_field_static_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktemplate',
            name='lanuage',
            field=models.CharField(blank=True, choices=[('cs', 'Czech Republic'), ('de', 'Germany')], max_length=128, null=True),
        ),
    ]
