# Generated by Django 5.1.4 on 2025-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_blocktemplate_lanuage'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_combined',
            field=models.BooleanField(default=False),
        ),
    ]
