# Generated by Django 5.1.4 on 2025-01-21 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_field_is_combined'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
