# Generated by Django 5.1.4 on 2025-01-21 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_field_uuid_blocktemplate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktemplate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
