# Generated by Django 5.1.4 on 2025-01-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_blocktemplate_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionfield',
            name='is_combined',
            field=models.BooleanField(default=False),
        ),
    ]
