# Generated by Django 5.1.4 on 2025-01-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_descriptionfield_is_combined'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='allow_duplication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('date', 'Date'), ('boolean', 'Boolean'), ('phone', 'Phone'), ('button', 'Button')], max_length=50),
        ),
    ]
