# Generated by Django 5.1.4 on 2025-01-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_field_allow_duplication_alter_field_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionfield',
            name='allow_duplication',
            field=models.BooleanField(default=False),
        ),
    ]
