# Generated by Django 5.1.4 on 2025-01-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_descriptionfield_allow_duplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_dublicate', models.BooleanField(default=False)),
                ('block_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combined_blocks', to='app.blocktemplate')),
                ('fields', models.ManyToManyField(blank=True, related_name='duplicates', to='app.field')),
            ],
        ),
    ]
