# Generated by Django 5.1.4 on 2025-01-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_combinedblock_description_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedblock',
            name='description_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combined_blocks', to='app.descriptionfield'),
        ),
    ]
