# Generated by Django 5.1.4 on 2025-01-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_combinedblock_description_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionfield',
            name='allow_duplication',
        ),
        migrations.RemoveField(
            model_name='descriptionfield',
            name='is_combined',
        ),
        migrations.RemoveField(
            model_name='field',
            name='allow_duplication',
        ),
        migrations.RemoveField(
            model_name='field',
            name='is_combined',
        ),
    ]
