# Generated by Django 5.1.4 on 2025-01-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_descriptionfield_allow_duplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_combined',
            field=models.BooleanField(default=False),
        ),
    ]
