# Generated by Django 5.1.4 on 2025-01-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_field_is_combined'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionfield',
            name='is_combined',
            field=models.BooleanField(default=False),
        ),
    ]
