# Generated by Django 5.1.4 on 2025-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_librarytemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarytemplate',
            name='field',
        ),
        migrations.AddField(
            model_name='librarytemplate',
            name='field',
            field=models.ManyToManyField(blank=True, related_name='library_templates', to='app.field'),
        ),
    ]
