# Generated by Django 5.1.4 on 2025-01-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_librarytemplate_field_librarytemplate_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarytemplate',
            old_name='field',
            new_name='fields',
        ),
    ]
