# Generated by Django 5.1.4 on 2025-01-30 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_rename_field_librarytemplate_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarytemplate',
            name='combined_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='library_templates', to='app.combinedblock'),
        ),
        migrations.AlterField(
            model_name='librarytemplate',
            name='description_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='library_templates', to='app.descriptionfield'),
        ),
    ]
