# Generated by Django 5.1.4 on 2025-01-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_librarytemplate_combined_block_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
