# Generated by Django 5.1.4 on 2025-01-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_delete_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
