# Generated by Django 5.1.4 on 2025-02-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_delete_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
