# Generated by Django 5.1.4 on 2025-02-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_field_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarytemplate',
            name='fields',
        ),
        migrations.AddField(
            model_name='librarytemplate',
            name='fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_templates', to='app.field'),
        ),
    ]
