# Generated by Django 5.1.4 on 2025-02-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_librarytemplate_fields_librarytemplate_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarytemplate',
            old_name='fields',
            new_name='field',
        ),
    ]
