# Generated by Django 5.1.4 on 2025-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rename_fields_librarytemplate_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktemplate',
            name='library_templates',
            field=models.ManyToManyField(blank=True, to='app.librarytemplate'),
        ),
    ]
