# Generated by Django 5.1.4 on 2025-02-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_combinedblock_description_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarytemplate',
            name='combined_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_templates', to='app.combinedblock'),
        ),
        migrations.AlterField(
            model_name='librarytemplate',
            name='description_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_templates', to='app.descriptionfield'),
        ),
        migrations.AlterField(
            model_name='librarytemplate',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_templates', to='app.field'),
        ),
    ]
