# Generated by Django 5.1.4 on 2025-03-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_librarytemplate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocktemplate',
            old_name='library_templates',
            new_name='all_library_templates',
        ),
        migrations.AddField(
            model_name='blocktemplate',
            name='all_combined_blocks',
            field=models.ManyToManyField(blank=True, to='app.combinedblock'),
        ),
        migrations.AddField(
            model_name='blocktemplate',
            name='all_description_fields',
            field=models.ManyToManyField(blank=True, to='app.descriptionfield'),
        ),
        migrations.AddField(
            model_name='blocktemplate',
            name='all_fields',
            field=models.ManyToManyField(blank=True, to='app.field'),
        ),
    ]
