# Generated by Django 5.1.4 on 2025-03-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_librarytemplate_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarytemplate',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_templates', to='app.field'),
        ),
    ]
