# Generated by Django 5.1.4 on 2025-03-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_librarytemplate_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocktemplate',
            old_name='lanuage',
            new_name='language',
        ),
    ]
