# Generated by Django 5.1.4 on 2025-03-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_blocktemplate_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktemplate',
            name='language',
            field=models.CharField(blank=True, choices=[('cs', 'Czech Republic'), ('de', 'Germany')], max_length=128, null=True),
        ),
    ]
