# Generated by Django 5.1.4 on 2025-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_blocktemplate_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='from_library',
            field=models.BooleanField(default=False),
        ),
    ]
