# Generated by Django 5.1.4 on 2025-04-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_field_from_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedblock',
            name='is_cloned',
            field=models.BooleanField(default=False),
        ),
    ]
