# Generated by Django 5.1.4 on 2025-04-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_combinedblock_is_cloned'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedblock',
            name='is_from_library_template',
            field=models.BooleanField(default=False),
        ),
    ]
