# Generated by Django 5.1.4 on 2025-04-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_combinedblock_is_copy_from_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedblock',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='app.combinedblock'),
        ),
    ]
