# Generated by Django 5.1.4 on 2025-03-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_fieldresponse_input_method_fieldresponse_input_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldresponse',
            name='input_method',
            field=models.CharField(blank=True, choices=[('paste', 'Paste'), ('keydown', 'Keydown'), ('unknown', 'Unknown')], max_length=128, null=True),
        ),
    ]
