# Generated by Django 5.1.4 on 2025-03-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_fieldresponse_input_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='language',
            field=models.CharField(blank=True, choices=[('cs', 'Czech Republic'), ('de', 'Germany')], max_length=128, null=True),
        ),
    ]
