# Generated by Django 5.1.4 on 2025-04-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_surveyresponse_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
